version: 2

jobs:
  build:
    docker:
      - image: cimg/php:8.1-browsers
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev --no-install-recommends && (yes || true) | sudo pecl install imagick      
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "composer.lock" }}
      #       - v1-dependencies-
      # - run:
      #     name: "Install Dependencies"
      #     command: composer install -n --prefer-dist
      # - save_cache:
      #     key: v1-dependencies-{{ checksum "composer.lock" }}
      #     paths:
      #       - ./vendor
      - run:
          name: "Install Dependencies"
          command: cd src/extra-bundle && composer install -n --prefer-dist
      - run:
          name: pwd
          command: echo pwd
      - run:
          name: "Run tests"
          command: cd src/extra-bundle && vendor/bin/phpunit
